import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './providers'
import { concat } from '@/utils'

import { Manrope } from 'next/font/google'


const manrope = Manrope({
  weight: ["600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});


import Header from "layout/Header";
import Backdrop from 'layout/Gradient'
import Navigation from '@/layout/Navigation'
import DebugContext from '@/utils/debugContext'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, }: { children: React.ReactNode }) {

  return (
    <html lang="en"
      className={concat(
        manrope.className,

        "2xl:text-[20.0px]", // 1960px
        "xl:text-[19.0px]", // 1566px
        "lg:text-[19.0px]", // 1324px
        "md:text-[19.0px]", // 915px
        "sm:text-[3.0vw]", // 640px
        "xsm:text-[3.40vw]", // 460px

        "text-[17px]"
      )}>

      <Providers>
        <body className={manrope.className}>
          <Header />
          {/* <DebugContext /> */}
          <Navigation />
          <Backdrop />
          <article
            className={concat(
              // Layout
              "max-w-[1200px]",
              "xl:pl-[100px]", // Show space for navigation menu
              "lg:px-[5em]", // Hidden when viewport reaches "1324px"
              "px-0 sm:px-[6vw]",
              "mx-auto"
            )}>
            {children}
          </article>
        </body>
      </Providers>
    </html>
  )
}
